version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: c05-mongodb
    ports:
      - "27017:27017" 
    volumes:
      - mongodata:/data/db
    networks:
      - ism-dad-network

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c05-nodejs
    ports:
      - "5050:5050"
    environment:
      - MONGO_URI=mongodb://c05-mongodb:27017
    depends_on:
      - mongo
    networks:
      ism-dad-network:
        aliases:
          - c05-nodejs

volumes:
  mongodata:

networks:
  ism-dad-network:
    external: true
